echo OSTAVETE GO PROZORECOT OTVOREN DODEKA RABOTITE SO BAZATA
echo PRED DA GO STARTUVATE OVA PRVIOT PAT SMENETE JA LOZINKATA I PORTATA
echo VO ONIE KOI VI SE DADENI VO UPATSTVATA
plink odnadvor@bazi.finki.ukim.mk -ssh -pw B2eN66Rq3GXE7T8R -C -N -2 -L 1620:bazi.finki.ukim.mk:1521
